services:
  db:
    image: postgres:15.7
    restart: unless-stopped
    networks:
      - "backend-net"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-weather_oracle_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  backend-weather-oracle:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - "backend-net"
      - "weather-oracle-net"
      - "pub-net"
    ports:
      - "8095:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/weather_oracle_db}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-pass}

      APPLICATION_OPEN_WEATHER_API_KEY: ${APPLICATION_OPEN_WEATHER_API_KEY}
      APPLICATION_JWT_SECRET: ${APPLICATION_JWT_SECRET}

      APPLICATION_CORS_ALLOWED_ORIGIN_PATTERNS: ${APPLICATION_CORS_ALLOWED_ORIGIN_PATTERNS}
      APPLICATION_CORS_ALLOWED_ORIGINS: ${APPLICATION_CORS_ALLOWED_ORIGINS}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data:
    driver: local

networks:
  backend-net:
    driver: bridge
    internal: true
  weather-oracle-net:
    external: true
  pub-net:
    driver: bridge