version: '3.8'

services:
  db:
    image: postgres:15.7
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-weather_oracle_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  weather-oracle:
    image: ${IMAGE}
    ports:
      - "8095:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL:-jdbc:postgresql://db:5432/weather_oracle_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-pass}

      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY:?set in .env}
      OPEN_WEATHER_API_URL: ${OPEN_WEATHER_API_URL:-https://api.openweathermap.org}
      OPEN_WEATHER_API_JWT_SECRET: ${OPEN_WEATHER_API_JWT_SECRET:?set in .env}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data:
    driver: local