spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri:
#          jwk-set-uri:
            
  session:
    jdbc:
      table-name: SPRING_SESSION
    timeout: 2h

  application:
    name: weather-oracle

  datasource:
    username: $(DB_USERNAME)
    password: $(DB_PASSWORD)
    url: $(DB_URL)
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      hbm2ddl.auto: validate
      show_sql: true
      format_sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true

keycloak:
  realm:
  auth-server-url:
  resource:
  credentials:
    secret:
  use-resource-role-mappings:

openweather.api.key: $(OPENWEATHER_API_KEY)

server:
  port: 8080

logging:
  file:
    name: log-note.log
    path: /
  level:
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: OFF
    com.ddevuss.weather.oracle: INFO
    root: INFO