spring:
  application:
    name: weather-oracle
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      hbm2ddl.auto: validate
      show_sql: false
      format_sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true
      fail-on-null-creator-properties: true
      fail-on-missing-creator-properties: true

open.weather.api:
  key: ${OPEN_WEATHER_API_KEY}
  url: ${OPEN_WEATHER_API_URL:https://api.openweathermap.org}
  jwt:
    secret: ${REFRESH_TOKEN_SECRET}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
  packages-to-scan: com.ddevuss.weather.oracle.controller.api

server:
  port: 8080

logging:
  level:
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: OFF
    com.ddevuss.weather.oracle: INFO
    root: INFO
