spring:
  session:
    jdbc:
      table-name: SPRING_SESSION
    timeout: 2h
  application:
    name: weather-oracle
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      hbm2ddl.auto: validate
      show_sql: true
      format_sql: true

server:
  port: 8081